jj_webbing_homepage:
    path:     /
    defaults:
         _controller: JJWebbingBundle:Default:home

jj_platform_login:
    path:      /login
    defaults:
        _controller: JJWebbingBundle:Default:login
    
jj_platform_profil:
    path:      /profil
    defaults:
        _controller: JJWebbingBundle:Default:profil